version: '3'

services:
  auto:
    build: ./microservice
    depends_on:
      - mongo
    environment:
      - DB_MONGO=mongodb://mongo:27017/proyecto
  monolithic:
    build: ./monolithic
    depends_on:
      - mongo
    #environment:
    #  - DB_MONGO=mongodb://mongo:27017/proyecto
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auto
      - monolithic